apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-sample-java-v1
  labels:
    version: v1
    app: api-sample-java
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-sample-java
      version: v1
  template:
    metadata:
      labels:
        version: v1
        app: api-sample-java
    spec:
      containers:
      - name: api-sample-java
        image: prietor/api-sample-java:v1
        ports:
        - containerPort: 8080