apiVersion: v1
kind: Service
metadata:
  name: api-master-java
  labels:
    app: api-master-java
spec:
  type: NodePort
  selector:
    app: api-master-java
    version: v1
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 8180